/**
 * MENTORA DYNAMIC ARTIFACT REGISTRY
 * 
 * Dynamic runtime registry for interactive educational artifacts.
 * Stores artifacts generated by the AI Teacher Agent and dynamically compiled DSL sessions.
 * Completely decoupled from static preloaded fixtures.
 */

import { KineticTimeline } from '../../types/kinetic';

export interface LessonVariable {
  name: string;
  value: string | number;
  description: string;
  badge?: string;
}

export interface LessonOutlineItem {
  id: string;
  title: string;
  timestampMs: number;
  summary: string;
}

export interface RegisteredArtifact {
  id: string;
  semanticKey: string;
  title: string;
  domain: 'Algorithms' | 'Calculus' | 'Physics' | 'Systems' | 'Chemistry' | 'Computer Science' | 'General';
  timeline: KineticTimeline;
  outline: LessonOutlineItem[];
  variables: LessonVariable[];
  suggestedPrompts: string[];
}

class ArtifactRegistryClass {
  private artifacts: Map<string, RegisteredArtifact> = new Map();

  register(artifact: RegisteredArtifact) {
    this.artifacts.set(artifact.semanticKey, artifact);
  }

  get(semanticKey: string): RegisteredArtifact | undefined {
    return this.artifacts.get(semanticKey);
  }

  getAll(): RegisteredArtifact[] {
    return Array.from(this.artifacts.values());
  }

  clear() {
    this.artifacts.clear();
  }

  findByQuery(query: string): RegisteredArtifact | undefined {
    const q = query.toLowerCase();
    for (const art of this.artifacts.values()) {
      if (
        art.title.toLowerCase().includes(q) ||
        art.semanticKey.toLowerCase().includes(q) ||
        art.domain.toLowerCase().includes(q)
      ) {
        return art;
      }
    }
    return undefined;
  }
}

export const ArtifactRegistry = new ArtifactRegistryClass();
